services:
  pg-database:
    image: postgres:15
    environment:
      - POSTGRES_USER:root
      - POSTGRES_PASSWORD:root
      - POSTGRES_DB:ny_taxi
    volumes:
      - "d:/data-engineering/01-docker-terraform/2_docker_sql/ny_taxi_postgres-db:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    networks:
      - pg-network
  pg-network:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8081:80"
    networks:
      - pg-network

networks:
  pg-network:

