services:
  postgres: 
    image: postgres:15
    environment:
      POSTGRES_USER: cynthia
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: data_engineering
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "cynthia"]
      interval: 5s
      retries: 5
      start_period: 30s
    restart: always


docker run -it \
 -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v d:/data-engineering/01-docker-terraform/2_docker_sql/ny_taxi_postgres-db:/var/lib/postgresql/data \
  -p 5432:5432 \
postgres:15 
    

# creating a pgadmin docker image
docker run -it \
  -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
  -e PGADMIN_DEFAULT_PASSWORD="root" \
  -p 8080:80 \
  dpage/pgadmin4

# create a docker network
docker network create pg-network

docker run -it \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v d:/data-engineering/01-docker-terraform/2_docker_sql/ny_taxi_postgres-db:/var/lib/postgresql/data \
  -p 5432:5432 \
  --network=pg-network \
  --name pg-database \
postgres:15  


docker run -it \
  -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
  -e PGADMIN_DEFAULT_PASSWORD="root" \
  -p 8080:80 \
  --network=pg-network \
  --name pgadmin \
dpage/pgadmin4

# Make a variable URL

export URL="https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"

python ingest_data.py \
	--user=root \
	--password=root \
	--host=localhost \
	--port=5432 \
	--db=ny_taxi \
	--table_name=yellow_taxi_trips \
	--url=${URL} 


